### ISSUE TITLE
About naming output files

### ISSUE THREAD

**Issue by MaisonCX** [diracdeltas/demucs4max#12]
Hey all,
First of all, thanks so much for that tite engine. Running like a truck !

It's about naming output files. I red plenty of times the Syntax help, but can't figure out. I even ask IA bots to help me. But still can't work this out.

In relative path mode, i wanna save the new files with that synthaxe {nameof the track} with {stem} as :"nameofthetrack-stem}.
For example, for the track "Pal Joey-We show off". If i wanna extract the vocal stem "vocal", i want to have a output files named "Pal Joey-We show off-vocal".

Any body have an idea on what synthaxe i should write ?

Best regards fam
Love
X

**Comment by diracdeltas** [comment]
hey great to hear. demucs actually has an option for filename, documented here: https://github.com/facebookresearch/demucs/blob/e976d93ecc3865e5757426930257e200846a520a/demucs/separate.py#L35-L41

so in your local install of demucs, you'll want to edit this line of code in demucs.js: https://github.com/diracdeltas/demucs4max/blob/main/demucs.js#L44

replace it with 
```
const cmd = `demucs -n ${MODEL_NAME} --filename "{track}-{stem}.{ext}" "${filename}"`
```

**Comment by MaisonCX** [comment]
ALRIGHT ! Thanks a lot & garonne !
That might gonna take a while to process that ... 
happy end of the year ☺

**Comment by MaisonCX** [comment]
Update : works fine writing "{track}-{stem}.{ext}", without doing any code change.
